#!/bin/bash

if [ "$(whoami)" == "root" ]; then
    exit 1
fi

ruta=$(pwd)

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k

# Copiando Archivos de Configuración

rm -r ~/.config/kitty
cp -rv $ruta/kitty ~/.config/

rm -r ~/.config/zsh
cp -rv $ruta/zsh ~/.config/

# Copia de configuracion de .p10k.zsh y .zshrc
rm -rf ~/.zshrc
cp -v $ruta/.zshrc ~/.zshrc
rm -rf ~/.p10k.zsh
cp -v $ruta/.p10k.zsh ~/.p10k.zsh

# Copian util scripts
cp -rv $ruta/bin/* ~/.local/bin/

# Copiando Fuentes

if [ -d "/Library/Fonts" ]; then
    # Si /Library/Fonts existe, copiar a Library Fonts
    cp -rv $ruta/fonts/* ~/Library/Fonts/
else
    # Si /Library/Fonts no existe, copiar a /Biblioteca/Fuentes
    cp -rv $ruta/fonts/* ~/Biblioteca/Fuentes/
fi

# Agregando pokemon color scripts
git clone git@gitlab.com:phoneybadger/pokemon-colorscripts.git

$ruta/pokemon-colorscripts/install.sh
pokemon-colorscripts -n charizard

source ~/.zshrc
cd ..
rm -rf ./dotfiles/
cd ..